feat: update "asyncapi-adoption-metrics" to v2.4.5
asyncapi/cli pull request #1369
Opened 2024-04-15 15:31 UTC by peter-rr

This PR will update "asyncapi-adoption-metrics" dependency to latest version.

2024-04-18 10:09 UTC, peter-rr commented
/ptal

2024-04-24 09:15 UTC, KhudaDad414 approved these changes
LGTM!

2024-04-24 11:21 UTC, Shurtu-gal approved these changes
LGTM 🎸

2024-04-24 11:24 UTC, Shurtu-gal requested changes

2024-04-24 11:24 UTC, Shurtu-gal commented on package.json
Should we update to the latest [`2.4.7`](https://github.com/smoya/asyncapi-adoption-metrics/releases/tag/v2.4.7) version ?

2024-04-24 13:07 UTC, peter-rr commented on package.json
Sure! Gonna update it 👍

2024-04-24 16:00 UTC, Shurtu-gal approved these changes

2024-04-24 17:41 UTC, peter-rr commented
/rtm

2024-04-24 17:41 UTC, merged