feat: add '--status' flag to `asyncapi config analytics` command
asyncapi/cli pull request #1386
Opened 2024-04-23 16:24 UTC by peter-rr

This PR will add the --status flag to the analytics command in order to show the current status of analytics for metrics collection.

**Related issue(s)**
Relates to #859

2024-04-23 16:28 UTC, peter-rr commented
⚠️  PR still in progress. Not ready for review yet.

2024-04-30 18:20 UTC, peter-rr commented
/ptal

2024-04-30 19:01 UTC, Shurtu-gal requested changes

2024-04-30 19:01 UTC, Shurtu-gal commented on src/commands/config/analytics.ts
> +    status: Flags.boolean({ char: 's', description: 'show analytics current status' }),
```suggestion
    status: Flags.boolean({ char: 's', description: 'show current status of analytics' }),
```

2024-05-02 08:09 UTC, peter-rr commented on src/commands/config/analytics.ts
> +    status: Flags.boolean({ char: 's', description: 'show analytics current status' }),
Yeah, much more clear like that 👍

2024-05-02 09:01 UTC, KhudaDad414 approved these changes
LGTM!

2024-05-02 09:01 UTC, KhudaDad414 commented on src/commands/config/analytics.ts
> +          this.log('\nAnalytics are enabled. Please append the "--disable" flag to the command in case you prefer to disable analytics.\n');
```suggestion
          this.log('\nAnalytics are enabled.\n');
```
let's not encourage this, since we want the users to keep it enabled.

2024-05-02 11:23 UTC, Shurtu-gal approved these changes
LGTM

2024-05-02 12:08 UTC, peter-rr commented
/rtm

2024-05-02 12:09 UTC, merged