test: replicate incorrect bundling and missing assertions part of #1323
asyncapi/cli pull request #1389
Opened 2024-04-24 11:56 UTC by francocm

**Description**

- Fixes missing assertion on spec to be `true` in `bundle.test.ts`. Existing tests also failing.
- Replicates the problem described in #1323

**Related issue(s)**

Replicates #1323

2024-04-26 19:24 UTC, francocm commented on test/integration/bundle/bundle.test.ts
> +      expect(validateGeneratedSpec('test/integration/bundle/final.yaml', specv3)).to.be.true
@peter-rr I've updated the PR slightly regarding the way assertions are done, and also which referenced files etc are used for comparison.

I spent some time trying to get to the root cause, but I am suspecting it's originating from https://github.com/asyncapi/bundler. This repo uses `0.4.0`. I noticed that `0.5.0` is available, but the upgrade to `0.5.0` is not straightforward. A lot of tests started failing after upgrading, as well as I noticed that `0.5.0` changed the signature and configuration options.

So this requires deeper investigation and also a plan for upgrade.

2024-04-30 16:29 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      expect(validateGeneratedSpec('test/integration/bundle/final-asyncapi.yaml', spec)).to.be.true;
Sorry, I was mistaken here: the assertion should be 'true' instead.

2024-04-30 16:34 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      expect(validateGeneratedSpec('test/integration/bundle/final.yaml', spec)).to.be.true;
Also I was mistaken here: the assertion should be 'false'.

2024-04-30 16:43 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      assertSpecsEqual('test/integration/bundle/final.yaml', spec);
```suggestion
      expect(validateGeneratedSpec('test/integration/bundle/final.yaml', spec)).to.equal(false);
```

2024-04-30 16:44 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      assertSpecsEqual('test/integration/bundle/final.yaml', spec);
```suggestion
      expect(validateGeneratedSpec('test/integration/bundle/final.yaml', spec)).to.equal(true);
```

2024-04-30 16:45 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      assertSpecsEqual('test/integration/bundle/final.yaml', specv3);
```suggestion
      expect(validateGeneratedSpec('test/integration/bundle/final.yaml', specv3)).to.equal(true);
```

2024-04-30 17:07 UTC, peter-rr requested changes
Left some comments 😄

2024-04-30 17:07 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +function assertSpecsEqual(filePath: string, spec: string) {
We would prefer to use the `validateGeneratedSpec` function instead, so we can make the assertion part more explicit and readable for each test. Besides, in that way we make sure we're following the same assertion style used to test the rest of asyncapi commands so far.

2024-04-30 17:07 UTC, peter-rr commented on test/integration/bundle/bundle.test.ts
> +      assertSpecsEqual('test/integration/bundle/final.yaml', spec);
The `description` of the documents compared should be different here.

2024-05-09 15:59 UTC, francocm commented
I've pulled and synced the changes from `master` branch into here, and the good news is after #1415  (@aeworxet), the original issue mentioned in #1323 seems solved.

However, the corrected tests are now showing 1 new issue coming probably from the bundler.

The bundler, since `0.5.0`, makes it clear that objects must be dereferenced to the maximum extent possible. At least that's how I'm interpreting [this](https://github.com/asyncapi/bundler/blob/0ae7ede/README.md#dereference-of-the-external-references).

However, when running the tests, for ASyncAPI `v3.0.0` docs, it's leaving the following behind:

```yaml
components:
  messages:
    TestMessage:
      payload:
        type: string
      x-origin: '#/components/messages/TestMessage'
```

This happens for both `x-origin` use and without. In case of `x-origin`, it does get referenced through `x-origin` itself, but I believe this shouldn't matter. In fact, with `x-origin: false`, then there's no references at all, yet still present. The content gets dereferenced successfully, just not cleaned up.

Right now this is the only thing keeping it failing.

@peter-rr @Amzani @Souvikns @Shurtu-gal any thoughts how you'd like to proceed?

Options I can think of:
1. Raise it as a separate bug, and for now I remove the 'offending' part from the test comparison, and this gets solved.
2. It's not a bug (please verify my interpretation), so will simply fix the test and this gets solved.
3. Get it resolved in bundler and keep this PR waiting until that gets fixed.

Thanks!

2024-05-13 12:33 UTC, francocm commented
@aeworxet 

Thanks for the analysis.

Worth adding that although this component is ignored, when `x-origin: true` is used, it's still being updated, as in that scenario, the `x-origin: '#/components/messages/TestMessage'` gets added, pointing to itself.

I have updated my PR to consider this outcome as expected in the tests, since the scope of this PR is on the issue raised in #1323 and:

1. assertions that replicated the original problem
2. assertions that were not actually being checked on existing tests
3. will now act as better regression test library for future changes

Probably anything else needs to be done in a separate place, and could be tracked in a new issue + linked to the https://github.com/APIDevTools/json-schema-ref-parser/issues/349 you raised.

@peter-rr I've updated the PR with feedback, tests should be passing, and it's no longer a draft. Kindly let me know your thoughts at this stage.

Thanks 🙂

2024-05-14 17:08 UTC, peter-rr commented
/update

2024-05-14 17:52 UTC, peter-rr commented
> Probably anything else needs to be done in a separate place, and could be tracked in a new issue + linked to the [APIDevTools/json-schema-ref-parser#349](https://github.com/APIDevTools/json-schema-ref-parser/issues/349) you raised.

Yeah, I agree with this 👍 
Once the new tests are passing I think we could proceed to close this bug

2024-05-15 09:00 UTC, peter-rr commented
/update

2024-05-15 09:56 UTC, francocm commented
Hi @peter-rr,

Thanks for following up. I've run `npm run lint:fix` and pushed it back.

Running `npm run test` seems to be running fine here?

```
  129 passing (45s)
```

Full log:

```
➜  asyncapi-cli git:(fix/1323/bundleNotBundlingExternalFiles) ✗ npm run test    
> @asyncapi/cli@1.14.0 pretest
> npm run build


> @asyncapi/cli@1.14.0 build
> rimraf lib && node scripts/fetch-asyncapi-example.js && tsc && oclif manifest && echo "Build Completed"

Fetched ZIP file
Unzipped all examples from zip
 ›   Warning: oclif update available from 4.5.0 to 4.8.8.
wrote manifest to /Users/<username_redacted>/workspace/asyncapi-cli/oclif.manifest.json
Build Completed

> @asyncapi/cli@1.14.0 test
> npm run test:unit


> @asyncapi/cli@1.14.0 test:unit
> cross-env NODE_ENV=development TEST=1 CUSTOM_CONTEXT_FILENAME="test.asyncapi-cli" CUSTOM_CONTEXT_FILE_LOCATION="" nyc --extension .ts mocha --require ts-node/register --require test/helpers/init.js --reporter spec --timeout 100000 "test/**/*.test.ts"



  bundle
    ✔ should throw error message if the file path is wrong

  bundle spec v3

  config:analytics
    with disable flag
    with enable flag
    with no flags
    with status flag

  config
    config:versions

  config:context, positive scenario
    config:context:current
    config:context:list
    config:context:add
    config:context:add
    config:context:edit
    config:context:use
    config:context:remove
    config:context:init
    config:context:init
    config:context:init
    config:context:init

  config:context, negative scenario
    config:context:add
    config:context:add
    config:context:add
    config:context:add

  config:context, negative scenario
    config:context:list

  convert
    with file paths
    with no arguments
    with no context file
    with target-version flag
    with output flag

  diff
    should handle AsyncAPI v3 document correctly
    with file paths, and there are no difference between the files
    yaml output: with file paths, and there are no difference between the files
    with file paths, and getting all changes
    with file paths, and getting breaking changes
    with file paths, and getting non-breaking changes
    with file paths, and getting unclassified changes
    with file paths, and getting all changes, passing flag
    YAML output, getting all changes
    should show error on breaking changes
    Markdown output with subtype as json, getting all changes
    Markdown output with subtype as yaml, getting all changes
    Other output with markdownSubtype flag provided, check for warning
    with logging diagnostics
    with custom standard file
    should throw error for invalid override path
    should throw error for invalid override json

  template
    should handle AsyncAPI v3 document correctly
    git clash
Generation failed
      ✔ should throw error if output folder is in a git repository (205ms)
    custom params
    disable-hooks
    debug
    no-overwrite
    should install template
Generator Error: Installation failed
    map-base-url

  models
    should handle AsyncAPI v3 document correctly
    for TypeScript
    for JavaScript
    for Python
    for Rust
    for C#
    for C++
    for Java
    for Go
    for Kotlin
    for Dart
    for PHP
    with logging diagnostics

  new
    create new file
    when asyncapi file already exists

  new glee
    creation of new project is successful
    when new project name already exists

  optimize
    no optimization needed
    with no arguments
    with no context file
    no-tty flag
    interactive terminal
    error if the asyncapi file is invalid

  validate
    with file paths
    with context names
    with no arguments
    with no context file
    with --log-diagnostics flag
    with --diagnostics-format flag
    with --fail-severity flag


  129 passing (45s)

-----------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                            
-----------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------
All files                    |   59.91 |     40.2 |   57.22 |   60.09 |                                                                                              
 lib                         |    79.7 |    51.54 |    87.5 |    79.5 |                                                                                              
  base.js                    |    83.9 |    56.75 |     100 |    83.9 | 63-64,94-95,132,140-153                                                                      
  flags.js                   |     100 |      100 |     100 |     100 |                                                                                              
  globals.js                 |    38.7 |        0 |       0 |    38.7 | 13-15,20-45                                                                                  
  parser.js                  |   89.74 |    60.97 |     100 |   89.47 | 96-98,100-102,121,124                                                                        
 lib/commands                |    90.9 |    73.71 |     100 |   90.82 |                                                                                              
  bundle.js                  |   86.48 |    55.55 |     100 |   86.48 | 26-30,57-58                                                                                  
  convert.js                 |   94.87 |    77.77 |     100 |   94.87 | 54,60                                                                                        
  diff.js                    |   88.49 |    78.33 |     100 |   88.49 | 49,71,90,107,117,138,182-184,186,194,229,256                                                 
  optimize.js                |   92.37 |     73.4 |     100 |   92.17 | 87,94-104,113                                                                                
  validate.js                |   95.65 |       75 |     100 |   95.65 | 18                                                                                           
 lib/commands/config         |   86.88 |    76.47 |     100 |   86.44 |                                                                                              
  analytics.js               |   80.55 |    69.23 |     100 |   80.55 | 35-48                                                                                        
  versions.js                |      96 |      100 |     100 |   95.65 | 26                                                                                           
 lib/commands/config/context |   75.64 |    17.77 |     100 |   75.64 |                                                                                              
  add.js                     |      84 |       50 |     100 |      84 | 19-20,25-26                                                                                  
  current.js                 |   58.33 |     7.69 |     100 |   58.33 | 16-29                                                                                        
  edit.js                    |   70.83 |        0 |     100 |   70.83 | 19-27                                                                                        
  init.js                    |     100 |      100 |     100 |     100 |                                                                                              
  list.js                    |   86.36 |       50 |     100 |   86.36 | 14-15,28                                                                                     
  remove.js                  |   69.56 |        0 |     100 |   69.56 | 18-26                                                                                        
  use [...]

2024-05-15 09:57 UTC, francocm commented
Just realised, if it helps I'm using Node 20:

```
➜  asyncapi-cli git:(fix/1323/bundleNotBundlingExternalFiles) ✗ node --version
v20.12.2
➜  asyncapi-cli git:(fix/1323/bundleNotBundlingExternalFiles) ✗ npm --version 
10.5.0
➜  asyncapi-cli git:(fix/1323/bundleNotBundlingExternalFiles) ✗ 
```

2024-05-15 10:26 UTC, peter-rr commented
> Just realised, if it helps I'm using Node 20

Thanks @francocm for the tip 👍 I've tried with v20 but still getting the errors. Also now I'm getting many errors during the building process after updating CLI to the latest version 1.14.0. Even working on master branch. Let me investigate why I'm getting those results 🤔  and I'll get back to you.

2024-05-15 11:39 UTC, aeworxet commented
@peter-rr 
Can you please try cloning, npm-installing, and running your tests from zero? Sometimes there are manual changes you completely forgot you made, and they are not displayed with `git status` because files are in `.gitignore`.
Knowing the logic of `Bundler`, it explicitly compares [the integer part of the `asyncapi` property of the second AsyncAPI Document](https://github.com/asyncapi/bundler/blob/master/src/util.ts#L82) with [the integer part of the `asyncapi` property of the first AsyncAPI Document](https://github.com/asyncapi/bundler/blob/master/src/util.ts#L74), and it is very hard to compare two integers incorrectly if no changes are introduced somewhere else in the code.

2024-05-16 16:00 UTC, peter-rr commented
Thanks @aeworxet 😄  I just needed npm-installing to include the latest version of `@oclif/core` dependency. Everything working fine now.

2024-05-16 16:10 UTC, peter-rr commented
@francocm 
LGTM 👍 All tests passing after the latest changes applied.

Now this PR needs to be reviewed by the codeowners before being merged.

2024-05-16 16:11 UTC, peter-rr commented
/ptal

2024-05-16 16:11 UTC, peter-rr commented
/update

2024-05-17 14:15 UTC, Shurtu-gal requested changes

2024-05-17 14:15 UTC, Shurtu-gal commented on test/integration/bundle/final-asyncapi-with-xorigin.yaml
@francocm could you add the spec files in [test/fixtures](https://github.com/asyncapi/cli/tree/master/test/fixtures) as can be seen for others.

2024-09-16 16:03 UTC, Shurtu-gal commented
still relevant

@francocm are you still working on this?

2025-01-09 14:05 UTC, Shurtu-gal commented
Closing this ref: https://github.com/asyncapi/cli/issues/1323#issuecomment-2579882693

2025-01-09 14:05 UTC, closed without merging

2025-02-01 07:43 UTC, aeworxet commented
UPDATE
https://github.com/APIDevTools/json-schema-ref-parser/issues/349#issuecomment-2628833419