chore: use ``node-fetch`` insted of ``request``
asyncapi/cli pull request #1422
Opened 2024-05-14 06:49 UTC by helios2003

**Description**
Using `node-fetch` library instead of `request` since the latter is deprecated. <br />
**Related issue(s)**
Fixes #1421

2024-05-14 07:15 UTC, Shurtu-gal commented
/update

2024-05-14 10:06 UTC, Amzani requested changes

2024-05-14 10:06 UTC, Amzani commented on scripts/fetch-asyncapi-example.js
> +    fetch(SPEC_EXAMPLES_ZIP_URL)
Error handling can be improved by wrapping by a try/catch block (see: https://github.com/node-fetch/node-fetch?tab=readme-ov-file#handling-exceptions)

2024-05-14 10:06 UTC, Amzani commented on scripts/fetch-asyncapi-example.js
> +        file.on('close', () => {
Listen also the the `error` event
```
file.on('error', (err) => {
                    reject(err);
                });
```

2024-05-14 11:29 UTC, helios2003 commented
Done with the changes @Amzani

2024-05-14 11:33 UTC, helios2003 commented
Also, currently, we are using `node-fetch` v2.0.0 because we are using CommonJS syntax. The library only supports ES6 module syntax in the updated v3, so should we change it? (Even though they mention that critical bug fixes will be published for v2)
Ref: https://www.npmjs.com/package/node-fetch#commonjs

2024-05-14 13:26 UTC, Amzani approved these changes
LGTM

2024-05-15 15:46 UTC, Shurtu-gal approved these changes

2024-05-15 15:46 UTC, Shurtu-gal commented
/rtm

2024-05-15 15:47 UTC, merged