feat: integrate `cupid` in cli using the `relation` command
asyncapi/cli pull request #143
Opened 2021-11-22 17:42 UTC by arjungarg07

**Description**

This PR integrates @asyncapi/cupid in cli using the `relation` command.

Command usage syntax:
`asyncapi relation <context-1/filepath1> <context-2/filepath2> <context-3/filepath3> ...`

It has one flag:
`--type` which determines the output syntax of the relations and if not provided, would output default output syntax.

**Related issue(s)**
#47

2021-12-02 19:47 UTC, fmvilas commented
Great stuff, @arjungarg07! My only concern is that the command is not a verb. We decided to follow the form `asyncapi VERB [NOUN]` and `relation` is not a verb. What about `visualize`?

```
asyncapi visualize context1/asyncapi1 context2/asyncapi2 ...
```

2021-12-03 16:16 UTC, arjungarg07 commented
Yeah @fmvilas , I did thought of using the verb `visualize` but I was skeptical about it since we are not actually visualizing the architecture right away but just getting the relations in desired output format and later pasting it in live editor to visualize.

2021-12-07 18:44 UTC, fmvilas commented
🤔 I see what you mean. Maybe it should be something like `asyncapi generate diagram`? It kinda collapses with `asyncapi generate` where we probably want to use Generator. But maybe we can use `asyncapi generate code` and `asyncapi generate docs` for those...

For sure it can't be `relation` as it's not a verb/command, just a noun. Any other ideas?

2021-12-07 19:59 UTC, arjungarg07 commented
What about `asyncapi generate relations` ?

2021-12-08 15:59 UTC, fmvilas commented
🤔 It might sound as you're generating the relations but the relations are already there, you're just "finding" them and generating a diagram, isn't it?

2021-12-09 20:44 UTC, arjungarg07 commented
I didn't think in that way, in that case `asyncapi generate diagram` would be good.

2021-12-10 15:24 UTC, fmvilas commented
Yeah, now what worries me is that clash with `asyncapi generate` command. There's a related conversation going on in #129.

2022-01-18 15:00 UTC, felixjung commented
What about `asyncapi relate`?

2022-01-24 15:25 UTC, arjungarg07 commented
> What about `asyncapi relate`?

Yeah, this could be done.
@derberg what do you think about it?

2022-01-27 15:31 UTC, fmvilas commented
Yeah, I still think it's better if we stick to `generate diagram` or similar. Always look at it from the point of view of the user who doesn't know the underlying technology and instead they expect the command to represent what they want to achieve. The tool used for this is irrelevant for them.

2022-05-24 16:49 UTC, derberg commented
@arjungarg07 hey is this one ready for review?

- can you remove 2 code smells?
- can you remove manual bump of the cli version from package.json and package-lock.json, as we do it by the bot, and it will constantly cause issues for you on a PR, conflicts you do not want to have

2022-11-17 15:44 UTC, derberg commented
@arjungarg07 hey, not sure if you noticed but `asyncapi generate` is now possible, so you can continue with this PR if you want

2022-11-27 10:45 UTC, arjungarg07 commented
@derberg what would be the final command look like? `asyncapi generate relation` ?

2023-03-27 07:45 UTC, derberg commented
@arjungarg07 yo, should we keep it open?

2023-03-27 11:00 UTC, arjungarg07 commented
@derberg I had some doubts, to be resolved(asked above in the thread). Maybe, would open a new PR.

2023-03-28 16:41 UTC, derberg commented
up to you 😃

2023-04-03 16:31 UTC, derberg commented
> to be resolved(asked above in the thread)

oh wait, sorry, which doubts are not yet solved?

2023-07-19 11:36 UTC, derberg commented
@arjungarg07 I'm guessing we should close it, right?

2023-07-29 17:23 UTC, chinma-yyy commented
> @arjungarg07 I'm guessing we should close it, right?

So does it mean that this issue is open to other contributors @derberg ??

2023-09-12 08:20 UTC, Shurtu-gal requested changes
Also, the example folder can be moved into https://github.com/asyncapi/cli/tree/master/test/fixtures

2023-09-12 08:20 UTC, Shurtu-gal commented on test/commands/relation.test.ts
@arjungarg07 there has been a recent change in the folder structure for tests in #712. This can be moved into https://github.com/asyncapi/cli/tree/master/test/integration.

2023-09-12 08:30 UTC, derberg commented
closing for now, I'm in touch with @arjungarg07 to start a process of looking for new maintainers for `cupid`

2023-09-12 08:30 UTC, closed without merging