feat: Implemented logic to output diagnostics log by adding additional output flag to validate cli command.
asyncapi/cli pull request #1563
Opened 2024-10-30 17:10 UTC by SahilDahekar

**Description**

- Added additional output flag param ```-o``` to output diagnostics log to a file.
- By default the diagnostics log will be printed in terminal.

**Related issue(s)**
Resolves #1095

2024-11-11 08:47 UTC, Souvikns commented
@SahilDahekar you have some lint issues. Can you fix them, so that we can start with the review?

2024-11-11 14:25 UTC, SahilDahekar commented
Hey @Souvikns , thanks for the response.  I have fixed the lint issues now and we can go ahead with review.

2024-11-13 05:22 UTC, Souvikns requested changes
Everything looks good just remove the commented code and we are good to go.

2024-11-13 05:23 UTC, SahilDahekar commented on src/core/parser.ts
> +// }
Yes

2024-11-13 05:50 UTC, Souvikns approved these changes

2024-11-13 05:51 UTC, Souvikns commented
/rtm

2024-11-13 05:51 UTC, merged