feat: added changeset configuration
asyncapi/cli pull request #1586
Opened 2024-12-06 19:49 UTC by akshatnema

## Description

This PR targets adding a changeset configuration for cli and gitHub action for cli.  

**Related issue(s)**

2024-12-06 20:53 UTC, Shurtu-gal submitted a review, later dismissed
LGTM

2024-12-06 20:54 UTC, Shurtu-gal commented
@akshatnema before merging could you change the contibuting.md to add changeset to be added for releases

2024-12-07 10:39 UTC, Shurtu-gal requested changes

2024-12-07 10:39 UTC, Shurtu-gal commented on Development.md
> +    "@asyncapi/generator": minor
Could you change it to CLI as it could be easily confused?

2024-12-07 10:39 UTC, Shurtu-gal commented on Development.md
> +     "name": "@asyncapi/generator",
Here also

2024-12-07 10:39 UTC, Shurtu-gal commented on Development.md
> +     "name": "@asyncapi/generator",
Here as well.

2024-12-07 11:58 UTC, Shurtu-gal approved these changes

2024-12-07 11:58 UTC, Shurtu-gal commented
/rtm

2024-12-07 11:58 UTC, merged

2024-12-07 12:00 UTC, Shurtu-gal commented
@Souvikns FYI we are shifting to changeset style of releases now. 

Discussion Thread: https://asyncapi.slack.com/archives/C07JW8SJK47

2024-12-09 05:03 UTC, aeworxet commented
@asyncapi/bounty_team