feat: enable proxy support in the cli
asyncapi/cli pull request #1608
Opened 2024-12-23 13:36 UTC by AayushSaini101

closes: https://github.com/asyncapi/cli/issues/862
Related: https://github.com/asyncapi/cli/issues/1508

2024-12-23 13:36 UTC, AayushSaini101 commented
As discussed with @Souvikns planning to create a global flags that is proxyHost and proxyPort that can easily help to integrate proxy supports with various commands of the CLI.

Asyncapi generate
Asyncapi validate
Asyncapi convert
Asyncapi optimise

2024-12-27 03:41 UTC, Souvikns requested changes
@AayushSaini101 can we have some tests for this.

2025-01-04 11:17 UTC, AayushSaini101 commented
> @AayushSaini101 can we have some tests for this.

Done @Souvikns

2025-01-04 11:59 UTC, Souvikns approved these changes
I see you have updated 3 command, [`convert`, `optimize`, `validate`], I don't see any tests for optimize commands, shouldn't you also add test for `optimize` command.

2025-01-05 07:23 UTC, AayushSaini101 commented
> I see you have updated 3 commands, [`convert`, `optimize`, `validate`], I don't see any tests for optimize commands, shouldn't you also add test for `optimize` command.

Added test case for all the commands thanks @Souvikns  : )

2025-01-05 07:23 UTC, AayushSaini101 commented
> I see you have updated 3 commands, [`convert`, `optimize`, `validate`], I don't see any tests for optimize commands, shouldn't you also add test for `optimize` command.

Added test case for all the commands thanks @Souvikns  : )

2025-01-05 07:24 UTC, Souvikns approved these changes
Perfect!

2025-01-05 07:26 UTC, AayushSaini101 commented
/rtm

2025-01-05 07:26 UTC, merged