feat: add Modelina configuration file support
asyncapi/cli pull request #430
Opened 2023-01-16 10:35 UTC by jonaslagoni

**Description**
Currently, it's hard to utilize the full feature suite of Modelina, because they are hidden behind callbacks (to allow full customization of model rendering). To enable these features we need to support a basic configuration file, that the user can use to customize the model generation phase when running the `asyncapi generate models` command.

This PR is just a proof of concept to be used for discussing how to proceed.

**Related issue(s)**
Related to https://github.com/asyncapi/modelina/issues/780

2023-01-16 10:55 UTC, fmvilas commented
I love the approach. Gives a ton of flexibility. Have you thought about how to handle dependencies? I mean, what if in this file I want to import one dependency like `lodash`? Where should it go? A local package.json might be too much given that I may not even be running the command from a Node.js project or a project at all 🤔 Maybe scanning the file first to install the dependencies in their latest version? 🤔

2023-01-16 11:23 UTC, jonaslagoni commented
I actually did not think about that, but definitely a valid concern 🤔 Hmm...

At the point where you need to create a node project to run the command, do you not think it will be easier to add your own integration instead of using the CLI? So you [have a script such as:](https://github.com/asyncapi/modelina/blob/next/examples/typescript-generate-example/index.ts)
```js
import { TypeScriptGenerator, TS_COMMON_PRESET } from '@asyncapi/modelina';
import SomeDependency from 'something';

const generator = new TypeScriptGenerator({
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        example: true
      }
    }
  ]
});

export async function generate(): Promise<void> {
  const models = await generator.generate(input);
  for (const model of models) {
    console.log(model.result);
  }
}
generate();
```

When we extend this feature to the AsyncAPI generator and templates, adding a solution that enables dependencies would be needed anyway... Might need to take a [page out of the AsyncAPI generator](https://github.com/asyncapi/generator/blob/f0daa471c6ea4a91a2c7f18d616c0de06c30dafc/lib/generator.js#L359) 🤔

2023-01-16 16:47 UTC, derberg commented
You could always provide a clear instruction on how one can bundle dependencies into the config script. This is how GitHub Actions work now. You bundle all the code into one file that GitHub workflow uses and dist code. So you have instruction, if you want config file to contain some external dependencies then install them and then bundle with `@vercel/ncc`.

Anyway it is more on modelina side, right? not cli. You provide guide there, and just add it as link in `description: 'Path to config file'`

2023-01-16 16:57 UTC, jonaslagoni commented
> You could always provide a clear instruction on how one can bundle dependencies into the config script. This is how GitHub Actions work now. You bundle all the code into one file that GitHub workflow uses and dist code. So you have instruction, if you want config file to contain some external dependencies then install them and then bundle with @vercel/ncc.

Can you clarify a bit more about what you mean? How bundling dependencies and code could work?

> Anyway it is more on modelina side, right? not cli. You provide guide there, and just add it as link in `description: 'Path to config file'`

Yea I think so too, see https://github.com/asyncapi/modelina/issues/780

But I want to see what functionality overlaps between CLI and Generator integrations before placing the logic in Modelina. Because arguments and the configuration file are overlapping in the CLI and the generator will probably have multiple configuration files (TBD), so I would rather not place common logic in Modelina before actually having proof it's needed.

I think the best way is to slowly progress and see what works and what does not. Always easy to remove stuff once we see commonalities 🙂

2023-01-16 17:27 UTC, derberg commented
> Can you clarify a bit more about what you mean? How bundling dependencies and code could work?

1. you create this:
```
import { TypeScriptGenerator, TS_COMMON_PRESET } from '@asyncapi/modelina';
import SomeDependency from 'something';

const generator = new TypeScriptGenerator({
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        example: true
      }
    }
  ]
});

export async function generate(): Promise<void> {
  const models = await generator.generate(input);
  for (const model of models) {
    console.log(model.result);
  }
}
generate();
```
2. then you install dependencies
3. then you install vercel bundler and run `ncc build your-config.js --external="@asyncapi/modelina"` (my assumption is that you do not want to bundle modelina in the bundle as it runs inside modelina anyway 😄 )
4. use generated `index.js` as the config that you pass to CLI

of course I did not test ☝🏼 with modelina and cli. Purely theoretical idea 😄 

---

> Because arguments and the configuration file are overlapping in the CLI and the generator will probably have multiple configuration files (TBD)

sorry I didn't get this. What overlaps, the `-c` that you add on CLI? with what exactly?

2023-01-16 17:46 UTC, jonaslagoni commented
> of course I did not test ☝🏼 with modelina and cli. Purely theoretical idea 😄

Ahh okay got it! Yea that is definitely another solution 👍 

> sorry I didn't get this. What overlaps, the -c that you add on CLI? with what exactly?

Oftentimes configuration files are used as the baseline, and then arguments overwrite it i.e. a user could do:
```
asyncapi generate models typescript -c="./typescript_model.js" --tsModelType="interface"
```

So even if the config file specified to output models to `class` the argument takes priority. Like this proof of concept does.

2023-01-17 11:19 UTC, derberg commented
> Oftentimes configuration files are used as the baseline, and then arguments overwrite it i.e. a user could do:

ah yes, but this can be solved by making these mutually exclusive. So if you use config, other props are ignored.

2023-09-12 08:18 UTC, Shurtu-gal requested changes

2023-09-12 08:18 UTC, Shurtu-gal commented on test/specification.yml
@jonaslagoni There has been a recent change in the folder structure for tests in #712. This can be moved into https://github.com/asyncapi/cli/tree/master/test/fixtures.

2023-09-12 08:18 UTC, Shurtu-gal commented on test/commands/generate/models.test.ts
Similarly, this and other files can be moved into the new folder. https://github.com/asyncapi/cli/tree/master/test/integration/generate

2023-10-02 05:31 UTC, Shurtu-gal commented on test/commands/generate/models.test.ts
Also the tests have been shifted to mocha now so some functions need to be changed.

2024-05-14 13:27 UTC, Amzani commented
@Shurtu-gal @jonaslagoni is this PR still needed?

2024-05-19 11:00 UTC, jonaslagoni commented
Its not needed no, once #1376 is merged it will automatically be included once we add it in Modelina 🙂

2024-05-19 11:00 UTC, closed without merging