docs: update Introduction section and add flowchart
asyncapi/cli pull request #552
Opened 2023-05-11 05:48 UTC by mhmohona

**Description**
Updated the Introduction section of the AsyncAPI CLI documentation and adds a flowchart to show the process flow of the CLI. The flowcharts shows the high-level process that occurs when using the CLI, helping users better understand the tool and its capabilities.

cc: @derberg @alequetzalli 

**Related issue(s)**

2023-05-11 14:11 UTC, derberg reviewed
Thank for the PR

I left some comments

Maybe example command usage should be here as well?

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +* Validation: AsyncAPI documents can be quickly and easily validated using the built-in validation tool, which ensures that the documents conform to the AsyncAPI specification and catches errors earl
`using the built-in validation tool` it is not build in, so please write `using the AsyncAPI Parser` and link to https://github.com/asyncapi/parser-js

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +* Generator: New AsyncAPI documents can be created based on templates using the CLI's Generator tool, saving time and effort when creating new APIs and ensuring that they follow best practices.
please mention that `Generator` through usage of https://github.com/asyncapi/generator/ and https://github.com/asyncapi/modelina enables generation of docs, apps, and models in different programming languages

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +* Format Conversion: AsyncAPI documents can be converted between different formats, such as YAML and JSON, using the CLI, which can be useful when working with a tool that requires a specific format.
please mention that conversion is handled thanks to integration of https://github.com/asyncapi/converter-js

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +* Templates: New AsyncAPI files can be quickly created using the CLI tool by selecting from a range of templates (MQTT, WebSockets, Kafka, and more).
this should be under `creation`, as this is how we support creation under `asyncapi new`

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +* Validation with Spectral: AsyncAPI documents can be validated with Spectral, providing feedback to verify that the document is within the correct format.
what do you mean? we are using JS Parser that internally uses spectral

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +```mermaid
please adjust diagram according to previous comments

also, makes sense to order the items, so first from left is creation (as you first create a file), then validation (and you validate after creation) and then generation, and conversion is marked as optional

also there are some more features, just install the CLI, write `asyncapi` in terminal and the output will tell you, like bundle, diff, optimize and more

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +    F --> |Suggests possible next steps to the user | I[CLI displays error message]
you mean in case of wrong command name?

2023-05-11 14:11 UTC, derberg commented on docs/index.md
> +This flowchart shows the high-level process that occurs when using the AsyncAPI CLI. The user starts by running a command (such as `validate`, `generate`, or `info`), which is processed by the CLI. T
what do you mean by `info`?

2023-05-11 23:41 UTC, alequetzalli commented
whoa cool, @mhmohona! ✨ I will let Lukasz review the technical accuracy piece first. Once he says it's correct, I will give it a TW editorial pass ✌🏽

2023-05-15 07:11 UTC, mhmohona commented on docs/index.md
> +    F --> |Suggests possible next steps to the user | I[CLI displays error message]
Yes

2023-05-15 07:12 UTC, mhmohona commented on docs/index.md
> +This flowchart shows the high-level process that occurs when using the AsyncAPI CLI. The user starts by running a command (such as `validate`, `generate`, or `info`), which is processed by the CLI. T
Typo :grimacing:

2023-05-15 17:02 UTC, derberg requested changes
left some comments, getting better!

2023-07-10 15:50 UTC, derberg commented
@mhmohona do you plan to continue with this one or should we close it?

2023-07-11 11:26 UTC, mhmohona commented
I actually forgot about this PR 😓 I will work on it.

2023-07-25 07:56 UTC, mhmohona commented on docs/index.md
> +* Format Conversion: The AsyncAPI CLI offers seamless conversion of AsyncAPI documents between different formats, such as YAML and JSON, through integration with the [AsyncAPI Converter](https://gith
@derberg, here only the format conversation should be removed or both start and format conversation?

2023-07-25 07:58 UTC, mhmohona commented
@derberg I have updated the changes as per review. Please have a look at it.

2023-07-26 15:18 UTC, derberg approved these changes
Thanks!!!

2023-07-26 15:47 UTC, derberg commented
/rtm

2023-07-26 15:47 UTC, merged

2023-07-26 15:47 UTC, derberg commented
@allcontributors please add @mhmohona for docs